services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9094:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver

  test_exporter:
    build: .
    ports:
      - "8000:8000"
